### ISSUE TITLE
Getting started and contributing

### ISSUE THREAD

**Issue by ElierHG** [pedrozadotdev/pocketblocks#50]
Hello Andre, 
Just wanted to say thank you for putting together this repo and for taking on the task of integrating Pocketbase with OpenBlocks. I think that is a great idea and it has so much potential! I have been looking for an alternative to Retool and Appsmith for a long time when I found this fork.
I would also like to work on this project and make any contributions I can but I'm kind of a new developer. I tried following the instructions in all of the readme files to set up a local dev environment, but I was not successful. Would you mind helping a newcomer start his journey in open source?

**Comment by pedrozadotdev** [comment]
Hi Elier. What kind of problem are you having?

**Comment by ElierHG** [comment]
> Hi Elier. What kind of problem are you having?

Hi, thanks you for replying!

I am able to start all three processes, the go server, the proxy server and the client app, but I think I am missing something. When I open the app in the browser, I only see the app shell, and some errors in the console. I'm sorry if my question sounds stupid, but I'm really new to codebases like this and I would like to get the app running in dev mode so can start getting familiar with it. Thanks in advance for your help. 

What my browser window looks like:
![image](https://github.com/user-attachments/assets/fac082a5-34a2-4f0d-af26-b0977466a9e4)

**Comment by pedrozadotdev** [comment]
Let me tell you the steps I take to work with this codebase...

First, make sure you have Node and Golang development environment set properly.

For example, here I have node v20.14.0 installed with NVM and go v1.22.4 installed traditionally.

Next, clone this repo, go to the project root directory, and run `go mod tidy`

Next, go to the proxy directory and run `yarn` then `yarn run client:prepare`, then `yarn run client:build`(I think the docs do not mention this because I considered you won't work with the client and server at the same time), then `yarn run build`(same here). You need to make sure to build the client and proxy at least one time to set up the server properly.

To work with the server, go to server dir and run `go run main.go serve` and open your browser at [localhost:8090](http://localhost:8090).

To work with the proxy, go to proxy dir and run `yarn run dev`(Make sure to run the server above in another terminal) and open your browser at [localhost:5173](http://localhost:5173)

To work with the client, go to proxy dir and run `yarn run client:dev`(Make sure to run the server above in another terminal) and open your browser at [localhost:5173](http://localhost:5173).

PS: As you can see, the proxy and client use the same port, so never run these two services at the same time. I never needed to run both so I think this is not a problem. Probably you won't need to work with the proxy at all, but always make sure to build it after building the client to update the client assets at the server... With time you will get this project as a whole and will understand why things work as they work.

**Comment by ElierHG** [comment]
Let me try that. 
Thank you, I really appreciate it! 👍
